Accept also non-url text
grishka/NearDrop pull request #112
Opened 2023-10-29 04:32 UTC by jxw1102

Currently NearDrop only accepts url type of textMetadata. 
This PR adds support to other type of text by storing them into pasteboard.

2023-11-25 11:38 UTC, sonique6784 requested changes

2023-11-25 11:38 UTC, sonique6784 commented on NearbyShare/InboundNearbyConnection.swift
> +    private var textType:Sharing_Nearby_TextMetadata.TypeEnum = .unknown
indentation

2023-11-25 11:38 UTC, sonique6784 commented on NearbyShare/InboundNearbyConnection.swift
> +            }
please review indentation

2023-11-25 11:38 UTC, sonique6784 commented on NearbyShare/InboundNearbyConnection.swift
> +            }
indentation

2024-02-01 12:02 UTC, PauloJSGG commented
Please merge this, it's super useful @jxw1102  @sonique6784

2024-02-19 11:48 UTC, TropicolX commented
@jxw1102 @sonique6784

2024-08-17 08:23 UTC, macx commented
Come on, @jxw1102 @sonique6784! I would suggest using Prettier, set up a project standard, save the files and submit the changes to be merged. It should be done within 20 Minutes. But this PR is over one year old. Guys…

2024-08-17 08:24 UTC, grishka commented
I do not want this feature in my app.

2024-08-22 10:14 UTC, pgamerx commented
> I do not want this feature in my app.

Why??
Everyone wants it

2024-08-22 11:12 UTC, grishka commented
Because sending something that doesn't visibly end up anywhere on the receiving side is confusing UX.

AirDrop on Mac does accept text from iPhones but it saves it as a .txt file. I can do this just to get this whole thing over with.

2024-08-22 11:14 UTC, PauloJSGG commented
Yes please 😃

2024-08-22 15:12 UTC, gramcraka commented
> Because sending something that doesn't visibly end up anywhere on the receiving side is confusing UX.
> 
> AirDrop on Mac does accept text from iPhones but it saves it as a .txt file. I can do this just to get this whole thing over with.

If we present a button that says "Copy" in the notification, that would be a less confusing UX.

2024-08-22 15:13 UTC, grishka commented
> If we present a button that says "Copy" in the notification, that would be a less confusing UX.

What if you accidentally dismiss that notification?

2024-08-22 15:39 UTC, pgamerx commented
Then you nearby share again

On Thu, 22 Aug, 2024, 8:43 pm Gregory K, ***@***.***> wrote:

> If we present a button that says "Copy" in the notification, that would be
> a less confusing UX.
>
> What if you accidentally dismiss that notification?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/grishka/NearDrop/pull/112#issuecomment-2304946665>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARCSGR2W4OY4H66TV3FLJD3ZSX52VAVCNFSM6AAAAAA6USA4L6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMBUHE2DMNRWGU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-08-24 09:23 UTC, flawnn commented
> > If we present a button that says "Copy" in the notification, that would be a less confusing UX.
> 
> What if you accidentally dismiss that notification?

Don't you have that UX Issue already with files you share?

2024-08-25 11:39 UTC, macx commented
> Because sending something that doesn't visibly end up anywhere on the receiving side is confusing UX.

So, Apple is wrong in terms of UX by enabling Continuity, which is enabling shared clipboard without any notification? If I copy or send anything, it's by action. The better UX could be, that I trust a device and the files will copy to a specific folder, or a notification button to accept and download it. But I would rather not click a button to accept the text I copied seconds ago – That is a bad UX.

The question I would ask: Do you want to copy a functionality with its limitations or UX fails, or could we do it better? I want to copy 60 % of the clipboard and 40 % of files from Android to Mac. Therefore, currently, this app is 60 % useless for me. But it has potential. Fingers cross to use the original in the future. If not, there a forks.

2024-08-25 13:31 UTC, grishka commented
> So, Apple is wrong in terms of UX by enabling Continuity, which is enabling shared clipboard without any notification?

Apple is able to identify which devices are yours and which aren't, with 100% reliability.

2024-09-22 00:12 UTC, closed without merging